export const Colors = {
  light: {
    text: "#11181C",
    textSecondary: "#4A5560",
    background: "#FFFFFF",
    backgroundElement: "#F1F3F5",
    border: "#D6DCE1",
    primary: "#1B5E8C",
    primaryText: "#FFFFFF",
    primaryContainer: "#D6E4F0",
    onPrimaryContainer: "#0D2A42",
    secondary: "#4A5560",
    secondaryContainer: "#D6E4E9",
    onSecondaryContainer: "#0B1E20",
    tertiary: "#6B4E00",
    tertiaryContainer: "#FFDD8A",
    onTertiaryContainer: "#221900",
    surface: "#FFFFFF",
    onSurface: "#11181C",
    surfaceVariant: "#F1F3F5",
    onSurfaceVariant: "#4A5560",
    outline: "#D6DCE1",
    outlineVariant: "#E8EAED",
    error: "#BA1A1A",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#410002",
    success: "#006C1A",
    successContainer: "#D6F5DC",
    onSuccessContainer: "#002309",
  },
  dark: {
    text: "#FFFFFF",
    textSecondary: "#B9C2CB",
    background: "#0E1114",
    backgroundElement: "#1B2126",
    border: "#2C343B",
    primary: "#7FB6DA",
    primaryText: "#0E1114",
    primaryContainer: "#0D2A42",
    onPrimaryContainer: "#D6E4F0",
    secondary: "#B9C2CB",
    secondaryContainer: "#0B1E20",
    onSecondaryContainer: "#D6E4E9",
    tertiary: "#FFDD8A",
    tertiaryContainer: "#221900",
    onTertiaryContainer: "#FFDD8A",
    surface: "#0E1114",
    onSurface: "#FFFFFF",
    surfaceVariant: "#1B2126",
    onSurfaceVariant: "#B9C2CB",
    outline: "#2C343B",
    outlineVariant: "#3B4247",
    error: "#FFB4AB",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    success: "#A8E6B3",
    successContainer: "#002309",
    onSuccessContainer: "#D6F5DC",
  },
} as const;

export const Spacing = {
  zero: 0,
  half: 4,
  one: 8,
  two: 12,
  three: 16,
  four: 24,
  five: 32,
  six: 48,
  seven: 64,
} as const;

export const BorderRadius = {
  none: 0,
  small: 8,
  medium: 12,
  large: 16,
  xlarge: 28,
  full: 9999,
} as const;

export const Typography = {
  displayLarge: {
    fontSize: 57,
    fontWeight: 400,
    lineHeight: "64px",
    letterSpacing: "-0.25px",
  },
  displayMedium: {
    fontSize: 45,
    fontWeight: 400,
    lineHeight: "52px",
    letterSpacing: "0px",
  },
  displaySmall: {
    fontSize: 36,
    fontWeight: 400,
    lineHeight: "44px",
    letterSpacing: "0px",
  },
  headlineLarge: {
    fontSize: 32,
    fontWeight: 600,
    lineHeight: "40px",
    letterSpacing: "0px",
  },
  headlineMedium: {
    fontSize: 28,
    fontWeight: 600,
    lineHeight: "36px",
    letterSpacing: "0px",
  },
  headlineSmall: {
    fontSize: 24,
    fontWeight: 600,
    lineHeight: "32px",
    letterSpacing: "0px",
  },
  titleLarge: {
    fontSize: 22,
    fontWeight: 600,
    lineHeight: "28px",
    letterSpacing: "0px",
  },
  titleMedium: {
    fontSize: 16,
    fontWeight: 500,
    lineHeight: "24px",
    letterSpacing: "0.15px",
  },
  titleSmall: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    letterSpacing: "0.1px",
  },
  bodyLarge: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: "24px",
    letterSpacing: "0.5px",
  },
  bodyMedium: {
    fontSize: 14,
    fontWeight: 400,
    lineHeight: "20px",
    letterSpacing: "0.25px",
  },
  bodySmall: {
    fontSize: 12,
    fontWeight: 400,
    lineHeight: "16px",
    letterSpacing: "0.4px",
  },
  labelLarge: {
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    letterSpacing: "0.1px",
  },
  labelMedium: {
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    letterSpacing: "0.5px",
  },
  labelSmall: {
    fontSize: 11,
    fontWeight: 500,
    lineHeight: "16px",
    letterSpacing: "0.5px",
  },
} as const;

export const MaxContentWidth = 600;
export const Breakpoints = {
  phone: 0,
  tablet: 600,
  desktop: 840,
} as const;
